config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :roasts
  resources :roasters
  resources :servings
  resources :reviewers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reviewer.rb
class Reviewer < ApplicationRecord
end

app/controllers/reviewers_controller.rb
class ReviewersController < ApplicationController
  before_action :set_reviewer, only: [:show, :edit, :update, :destroy]

  # GET /reviewers
  # GET /reviewers.json
  def index
    @reviewers = Reviewer.all
  end

  # GET /reviewers/1
  # GET /reviewers/1.json
  def show
  end

  # GET /reviewers/new
  def new
    @reviewer = Reviewer.new
  end

  # GET /reviewers/1/edit
  def edit
  end

  # POST /reviewers
  # POST /reviewers.json
  def create
    @reviewer = Reviewer.new(reviewer_params)

    respond_to do |format|
      if @reviewer.save
        format.html { redirect_to @reviewer, notice: 'Reviewer was successfully created.' }
        format.json { render :show, status: :created, location: @reviewer }
      else
        format.html { render :new }
        format.json { render json: @reviewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviewers/1
  # PATCH/PUT /reviewers/1.json
  def update
    respond_to do |format|
      if @reviewer.update(reviewer_params)
        format.html { redirect_to @reviewer, notice: 'Reviewer was successfully updated.' }
        format.json { render :show, status: :ok, location: @reviewer }
      else
        format.html { render :edit }
        format.json { render json: @reviewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviewers/1
  # DELETE /reviewers/1.json
  def destroy
    @reviewer.destroy
    respond_to do |format|
      format.html { redirect_to reviewers_url, notice: 'Reviewer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reviewer
      @reviewer = Reviewer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reviewer_params
      params.require(:reviewer).permit(:name, :location)
    end
end

app/helpers/reviewers_helper.rb
module ReviewersHelper
end

app/views/reviewers/_form.html.erb
<%= form_with(model: reviewer, local: true) do |form| %>
  <% if reviewer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reviewer.errors.count, "error") %> prohibited this reviewer from being saved:</h2>

      <ul>
      <% reviewer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :reviewer_name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :reviewer_location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviewers/edit.html.erb
<h1>Editing Reviewer</h1>

<%= render 'form', reviewer: @reviewer %>

<%= link_to 'Show', @reviewer %> |
<%= link_to 'Back', reviewers_path %>

app/views/reviewers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviewers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviewers.each do |reviewer| %>
      <tr>
        <td><%= reviewer.name %></td>
        <td><%= reviewer.location %></td>
        <td><%= link_to 'Show', reviewer %></td>
        <td><%= link_to 'Edit', edit_reviewer_path(reviewer) %></td>
        <td><%= link_to 'Destroy', reviewer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reviewer', new_reviewer_path %>

app/views/reviewers/new.html.erb
<h1>New Reviewer</h1>

<%= render 'form', reviewer: @reviewer %>

<%= link_to 'Back', reviewers_path %>

app/views/reviewers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reviewer.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @reviewer.location %>
</p>

<%= link_to 'Edit', edit_reviewer_path(@reviewer) %> |
<%= link_to 'Back', reviewers_path %>