config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :roasts
  resources :roasters
  resources :servings
  resources :reviewers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/roaster.rb
class Roaster < ApplicationRecord
end

app/controllers/roasters_controller.rb
class RoastersController < ApplicationController
  before_action :set_roaster, only: [:show, :edit, :update, :destroy]

  # GET /roasters
  # GET /roasters.json
  def index
    @roasters = Roaster.all
  end

  # GET /roasters/1
  # GET /roasters/1.json
  def show
  end

  # GET /roasters/new
  def new
    @roaster = Roaster.new
  end

  # GET /roasters/1/edit
  def edit
  end

  # POST /roasters
  # POST /roasters.json
  def create
    @roaster = Roaster.new(roaster_params)

    respond_to do |format|
      if @roaster.save
        format.html { redirect_to @roaster, notice: 'Roaster was successfully created.' }
        format.json { render :show, status: :created, location: @roaster }
      else
        format.html { render :new }
        format.json { render json: @roaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roasters/1
  # PATCH/PUT /roasters/1.json
  def update
    respond_to do |format|
      if @roaster.update(roaster_params)
        format.html { redirect_to @roaster, notice: 'Roaster was successfully updated.' }
        format.json { render :show, status: :ok, location: @roaster }
      else
        format.html { render :edit }
        format.json { render json: @roaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roasters/1
  # DELETE /roasters/1.json
  def destroy
    @roaster.destroy
    respond_to do |format|
      format.html { redirect_to roasters_url, notice: 'Roaster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roaster
      @roaster = Roaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roaster_params
      params.require(:roaster).permit(:name, :location)
    end
end

app/helpers/roasters_helper.rb
module RoastersHelper
end

app/views/roasters/_form.html.erb
<%= form_with(model: roaster, local: true) do |form| %>
  <% if roaster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(roaster.errors.count, "error") %> prohibited this roaster from being saved:</h2>

      <ul>
      <% roaster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :roaster_name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :roaster_location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/roasters/edit.html.erb
<h1>Editing Roaster</h1>

<%= render 'form', roaster: @roaster %>

<%= link_to 'Show', @roaster %> |
<%= link_to 'Back', roasters_path %>

app/views/roasters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roasters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roasters.each do |roaster| %>
      <tr>
        <td><%= roaster.name %></td>
        <td><%= roaster.location %></td>
        <td><%= link_to 'Show', roaster %></td>
        <td><%= link_to 'Edit', edit_roaster_path(roaster) %></td>
        <td><%= link_to 'Destroy', roaster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roaster', new_roaster_path %>

app/views/roasters/new.html.erb
<h1>New Roaster</h1>

<%= render 'form', roaster: @roaster %>

<%= link_to 'Back', roasters_path %>

app/views/roasters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @roaster.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @roaster.location %>
</p>

<%= link_to 'Edit', edit_roaster_path(@roaster) %> |
<%= link_to 'Back', roasters_path %>