config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :roasts
  resources :roasters
  resources :servings
  resources :reviewers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/serving.rb
class Serving < ApplicationRecord
end

app/controllers/servings_controller.rb
class ServingsController < ApplicationController
  before_action :set_serving, only: [:show, :edit, :update, :destroy]

  # GET /servings
  # GET /servings.json
  def index
    @servings = Serving.all
  end

  # GET /servings/1
  # GET /servings/1.json
  def show
  end

  # GET /servings/new
  def new
    @serving = Serving.new
  end

  # GET /servings/1/edit
  def edit
  end

  # POST /servings
  # POST /servings.json
  def create
    @serving = Serving.new(serving_params)

    respond_to do |format|
      if @serving.save
        format.html { redirect_to @serving, notice: 'Serving was successfully created.' }
        format.json { render :show, status: :created, location: @serving }
      else
        format.html { render :new }
        format.json { render json: @serving.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servings/1
  # PATCH/PUT /servings/1.json
  def update
    respond_to do |format|
      if @serving.update(serving_params)
        format.html { redirect_to @serving, notice: 'Serving was successfully updated.' }
        format.json { render :show, status: :ok, location: @serving }
      else
        format.html { render :edit }
        format.json { render json: @serving.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servings/1
  # DELETE /servings/1.json
  def destroy
    @serving.destroy
    respond_to do |format|
      format.html { redirect_to servings_url, notice: 'Serving was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_serving
      @serving = Serving.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def serving_params
      params.require(:serving).permit(:name)
    end
end

app/helpers/servings_helper.rb
module ServingsHelper
end

app/views/servings/_form.html.erb
<%= form_with(model: serving, local: true) do |form| %>
  <% if serving.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(serving.errors.count, "error") %> prohibited this serving from being saved:</h2>

      <ul>
      <% serving.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :serving_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/servings/edit.html.erb
<h1>Editing Serving</h1>

<%= render 'form', serving: @serving %>

<%= link_to 'Show', @serving %> |
<%= link_to 'Back', servings_path %>

app/views/servings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Servings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servings.each do |serving| %>
      <tr>
        <td><%= serving.name %></td>
        <td><%= link_to 'Show', serving %></td>
        <td><%= link_to 'Edit', edit_serving_path(serving) %></td>
        <td><%= link_to 'Destroy', serving, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Serving', new_serving_path %>

app/views/servings/new.html.erb
<h1>New Serving</h1>

<%= render 'form', serving: @serving %>

<%= link_to 'Back', servings_path %>

app/views/servings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @serving.name %>
</p>

<%= link_to 'Edit', edit_serving_path(@serving) %> |
<%= link_to 'Back', servings_path %>