config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :roasts
  resources :roasters
  resources :servings
  resources :reviewers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/roast.rb
class Roast < ApplicationRecord
  belongs_to :roaster
end

app/controllers/roasts_controller.rb
class RoastsController < ApplicationController
  before_action :set_roast, only: [:show, :edit, :update, :destroy]

  # GET /roasts
  # GET /roasts.json
  def index
    @roasts = Roast.all
  end

  # GET /roasts/1
  # GET /roasts/1.json
  def show
  end

  # GET /roasts/new
  def new
    @roast = Roast.new
  end

  # GET /roasts/1/edit
  def edit
  end

  # POST /roasts
  # POST /roasts.json
  def create
    @roast = Roast.new(roast_params)

    respond_to do |format|
      if @roast.save
        format.html { redirect_to @roast, notice: 'Roast was successfully created.' }
        format.json { render :show, status: :created, location: @roast }
      else
        format.html { render :new }
        format.json { render json: @roast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roasts/1
  # PATCH/PUT /roasts/1.json
  def update
    respond_to do |format|
      if @roast.update(roast_params)
        format.html { redirect_to @roast, notice: 'Roast was successfully updated.' }
        format.json { render :show, status: :ok, location: @roast }
      else
        format.html { render :edit }
        format.json { render json: @roast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roasts/1
  # DELETE /roasts/1.json
  def destroy
    @roast.destroy
    respond_to do |format|
      format.html { redirect_to roasts_url, notice: 'Roast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roast
      @roast = Roast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roast_params
      params.require(:roast).permit(:name, :roaster_id)
    end
end

app/helpers/roasts_helper.rb
module RoastsHelper
end

app/views/roasts/_form.html.erb
<%= form_with(model: roast, local: true) do |form| %>
  <% if roast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(roast.errors.count, "error") %> prohibited this roast from being saved:</h2>

      <ul>
      <% roast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :roast_name %>
  </div>

  <div class="field">
    <%= form.label :roaster_id %>
    <%= form.text_field :roaster_id, id: :roast_roaster_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/roasts/edit.html.erb
<h1>Editing Roast</h1>

<%= render 'form', roast: @roast %>

<%= link_to 'Show', @roast %> |
<%= link_to 'Back', roasts_path %>

app/views/roasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roasts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Roaster</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roasts.each do |roast| %>
      <tr>
        <td><%= roast.name %></td>
        <td><%= link_to roast.roaster.name, roast.roaster %></td>
        <td><%= link_to 'Show', roast %></td>
        <td><%= link_to 'Edit', edit_roast_path(roast) %></td>
        <td><%= link_to 'Destroy', roast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roast', new_roast_path %>

app/views/roasts/new.html.erb
<h1>New Roast</h1>

<%= render 'form', roast: @roast %>

<%= link_to 'Back', roasts_path %>

app/views/roasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @roast.name %>
</p>

<p>
  <strong>Roaster:</strong>
  <%= link_to @roast.roaster.name, @roast.roaster %>
</p>

<%= link_to 'Edit', edit_roast_path(@roast) %> |
<%= link_to 'Back', roasts_path %>